script: script/test

language: ruby

matrix:
  allow_failures:
    # An error occured while installing eventmachine
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    # "A fatal error has been detected by the Java Runtime Environment:
    #  Internal Error (sharedRuntime.cpp:843)"
    - rvm: jruby-19mode
      env: SSL=yes
    - rvm: 2.0.0

env:
  - SSL=no
  - SSL=yes

rvm:
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
