language: ruby
cache:
  bundler: true

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  fast_finish: true # do not wait for ruby-head to mark the build as finished
  allow_failures:
    - ruby-head

jobs:
  include:
    - stage: linting
      rvm: ruby-2.4.1 # Pre-installed on TravisCI
      install: true # Do not bundle install
      script: gem install rubocop --no-document && rubocop
    - stage: latest
      rvm: 2.6 # Run custom before/after scripts for latest supported Ruby version.
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: release
      rvm: 2.6
      install: true # Do not bundle install
      script: skip
      deploy:
        provider: rubygems
        api_key:
          secure: EqbOu9BQp5jkivJ8qvTo89f3J49KOByBueU3XulrJ2Kqm/ov4RDFsmp9/uHAnSLdmKSkzZaeq79t1AUNfKGX1ZqkKgq/Nw2BKGFnh5ZOjrkrRZR1Vm09OHxqiViEbtg+jZ8VOLY/iDFEkNIzuj9/H3iHGXC0XiKH2LTHOFH63Bs=
        gem: faraday
        on:
          tags: true
          repo: lostisland/faraday

stages:
  - linting
  - test
  - release

branches:
  only:
    - master
    - 0.1x
