before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
bundler_args: --standalone --without development
script: RUBYLIB=./bundle script/test

env:
  - SSL=no
  - SSL=yes

language: ruby

matrix:
  allow_failures:
    # "A fatal error has been detected by the Java Runtime Environment:
    #  Internal Error (sharedRuntime.cpp:843)"
    - rvm: jruby-18mode
      env: SSL=yes
    - rvm: jruby-19mode
      env: SSL=yes
    - rvm: jruby-20mode
      env: SSL=yes
    - rvm: jruby-21mode
      env: SSL=yes
    - rvm: jruby-head
    # random crashes
    - rvm: rbx
  fast_finish: true

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-head
  - rbx
