name: CI

on:
  pull_request:

  push:
    branches: [master, 0.1x]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Rubocop
      run: |
        gem install rubocop rubocop-performance --no-document
        rubocop --require rubocop-performance --format progress

    - name: Yard-Junk
      run: |
        gem install yard-junk --no-document
        yard-junk --path lib

  build:
    needs: [linting]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x, 2.7.0]

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Code Climate
      if: matrix.ruby == '2.6.x'
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Test
      run: bundle exec rake

    - name: Run Code Climate Test Reporter
      if: success() && matrix.ruby == '2.6.x'
      run: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      continue-on-error: true
